GoalApp/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  resource :session, only: [:new, :create, :destroy]
  resources :goals
end

GoalApp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

GoalApp/app/models/goal.rb
class Goal < ApplicationRecord
  validates :list_of_goal, :user_id, presence: true
  
  belongs_to :user,
    primary_key: :id,
    foreign_key: :user_id,
    class_name: 'User'
end

GoalApp/app/models/user.rb
class User < ApplicationRecord
  attr_reader :password
  validates :username, :session_token, :password_digest, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }
  after_initialize :ensure_session_token
  
  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    user && user.is_password?(password) ? user : nil
  end
  
  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end
  
  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64(16)
  end
  
  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end
  
  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64(16)
    self.save!
    self.session_token
  end
  
  has_many :goals,
    primary_key: :id,
    foreign_key: :user_id,
    class_name: 'Goal'
end

GoalApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :logged_in?, :current_user
  
  def login(user)
    @current_user = user
    session[:session_token] = user.reset_session_token!
  end
  
  def current_user
    @current_user ||= User.find_by_session_token(session[:session_token])
  end
  
  def logout
    current_user.reset_session_token!
    session[:session_token] = nil
  end
  
  def require_login
    redirect_to new_session_url unless logged_in?
  end
  
  def logged_in?
    !!current_user
  end
end

GoalApp/app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :not_users_page, only: [:show, :edit]
  
  def index
    @goals = Goal.all
    @goal = Goal.find(params[:id])
    render :index
  end
  
  def new
    @goal = Goal.new
    render :new
  end
  
  def edit
    @goal = current_user.goals.find(params[:id])
    render :edit
  end
  
  def show
    @goal = Goal.find(params[:id])
    render :show
  end
  
  def update
    @goal = current_user.goals.find(params[:id])
    if @goal.update_attributes(goal_params)
      redirect_to goal_url(@goal)
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :edit
    end
  end
  
  def destroy
    @goal = current_user.goals.find(params[:id])
    @goal.destroy
    redirect_to goals_url
  end
  
  def create
    @goal = Goal.new(goal_params)
    @goal.user_id = current_user.id
    if @goal.save
      redirect_to(goal_url(@goal))
    else
      flash.now[:errors] = @goals.errors.full_messages
      render :new
    end
  end
  
  private
  def goal_params
    params.require(:goal).permit(:list_of_goal)
  end
  
  def not_users_page
    unless current_user.goal_ids.include?(params[:id].to_i)
      flash[:errors] = ["You cannnot access the goals if another user."]
      redirect_to user_url(current_user)
    end
  end
end

GoalApp/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
    render :new
  end
  
  def create
    @user = User.find_by_credentials(params[:user][:username], params[:user][:password])
    if @user
      login(@user)
      redirect_to user_url(@user)
    else
      flash[:errors] = ['Invalid credentials']
      redirect_to new_session_url
    end
  end
  
  def destroy
    logout
    redirect_to new_session_url
  end



end

GoalApp/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    render :new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      login(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end
  
  def show
    @user = User.find(params[:id])
    render :show
  end
  
  private
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

GoalApp/app/helpers/application_helper.rb
module ApplicationHelper
end

GoalApp/app/views/goals/edit.html.erb
<h1>Edit Goal</h1>
<form action=" <%= goal_url(@goal) %>" method="post">
  <input type="hidden" name="_method" value="patch">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <textarea name="goal[list_of_goal]"><%= @goal.list_of_goal %></textarea>
  <br>
  <input type="submit" name="" value="Edit Goal">
</form>
<form action="<%= goal_url(@goal) %>" method="post">
  <input type="hidden" name="_method" value="delete">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="submit" name="" value="Delete Goal">
</form>

GoalApp/app/views/goals/index.html.erb
<ul>
  <% @goals.each do |goal| %>
    <li><%= goal.list_of_goal %></li>
    <a href="<%= edit_goal_url(goal) %>">Edit Goal</a>
  <% end %>
</ul>
<br>
<a href="<%= user_url(current_user) %>">Go to Your Profile</a>

GoalApp/app/views/goals/new.html.erb
<h1>Write Your Goals</h1>
<form action="<%= goals_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <textarea name="goal[list_of_goal]"></textarea>
  <br>
  <input type="submit" name="" value="Create Goal">
</form>

GoalApp/app/views/goals/show.html.erb
<%= @goal.list_of_goal %>
<br>
<a href="<%= goals_url %>">Go to All Your Goals</a>
<br>
<br>
<a href="<%= user_url(current_user) %>">Go to Your Profile</a>

GoalApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GoalApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if logged_in? %>
      <form action=" <%= session_url %>" method="post">
        <input type="hidden" name="_method" value="delete">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
        <input type="submit" name="" value="Log Out">
      </form>
    <% end %>
    <%= yield %>
  </body>
</html>

GoalApp/app/views/users/new.html.erb
<h1>New User</h1>
<form action="<%= users_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label for="username">Username</label>
    <input id="username" type="text" name="user[username]" value="">
  <label for="password">Password</label>
    <input id="password" type="password" name="user[password]" value="">
  <input type="submit" name="" value="Sign Up">
</form>

GoalApp/app/views/users/show.html.erb
<h1><%= @user.username %></h1>
<a href="<%= new_goal_url %>">Write Your Goals</a>
<br>
<br>
<a href="<%= goals_url %>">Your Goals</a>